# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: CarbonetesComprehensiveAnalysis@1
  inputs:
    registryUri: '367390716521.dkr.ecr.us-west-2.amazonaws.com'
    repoImageTag: 'apps/wordpress:latest'
    username: 'admin@hoolisoftware.com'
    password: '!Carbonetes99'
    timeout: 500