name: Release Jenkins Plugin

on:
  push:
    tags:
      - '*.*.*' # Triggers on version tags like 1.5.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo '<?xml version="1.0" encoding="UTF-8"?>' > ~/.m2/settings.xml
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"' >> ~/.m2/settings.xml
          echo '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' >> ~/.m2/settings.xml
          echo '         xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">' >> ~/.m2/settings.xml
          echo '  <servers>' >> ~/.m2/settings.xml
          echo '    <server>' >> ~/.m2/settings.xml
          echo '      <id>jenkins-releases</id>' >> ~/.m2/settings.xml
          echo "      <username>${{ secrets.JENKINS_USERNAME }}</username>" >> ~/.m2/settings.xml
          echo "      <password>${{ secrets.JENKINS_API_TOKEN }}</password>" >> ~/.m2/settings.xml
          echo '    </server>' >> ~/.m2/settings.xml
          echo '  </servers>' >> ~/.m2/settings.xml
          echo '  <profiles>' >> ~/.m2/settings.xml
          echo '    <profile>' >> ~/.m2/settings.xml
          echo '      <id>jenkins-release</id>' >> ~/.m2/settings.xml
          echo '      <properties>' >> ~/.m2/settings.xml
          echo '        <gpg.executable>gpg</gpg.executable>' >> ~/.m2/settings.xml
          echo "        <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>" >> ~/.m2/settings.xml
          echo '      </properties>' >> ~/.m2/settings.xml
          echo '    </profile>' >> ~/.m2/settings.xml
          echo '  </profiles>' >> ~/.m2/settings.xml
          echo '  <activeProfiles>' >> ~/.m2/settings.xml
          echo '    <activeProfile>jenkins-release</activeProfile>' >> ~/.m2/settings.xml
          echo '  </activeProfiles>' >> ~/.m2/settings.xml
          echo '</settings>' >> ~/.m2/settings.xml

      - name: Build and deploy to Jenkins repo
        run: mvn clean deploy -B
